apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cilium
  namespace: cilium
spec:
  channel: stable
  installPlanApproval: Automatic
  name: cilium
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: cilium.v1.10.8-x2ca7b2e
