apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cilium
  namespace: cilium
spec:
  channel: "1.12"
  installPlanApproval: Manual
  name: cilium
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: cilium.v1.12.4-x17747c2
